# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2018-03-16 06:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=30)),
                ('about_image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
                ('about_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='gradesInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grade', models.FloatField()),
                ('user_message', models.TextField()),
                ('ava_grade', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='phonesInf',
            fields=[
                ('phone_id', models.IntegerField(primary_key=True, serialize=False)),
                ('phone_type', models.CharField(max_length=30)),
                ('phone_image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
                ('phone_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_grant', models.BooleanField(default=False)),
                ('user_sex', models.CharField(max_length=5)),
                ('user_image', models.ImageField(default='pic_folder/no-img.jpg', upload_to='pic_folder/')),
                ('user_grades', models.FloatField(default=0.0)),
                ('user_passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workOrders',
            fields=[
                ('order_id', models.IntegerField(primary_key=True, serialize=False)),
                ('order_title', models.CharField(max_length=30)),
                ('order_details', models.CharField(max_length=255)),
                ('order_status', models.BooleanField(default=False)),
                ('order_grade', models.FloatField()),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.phonesInf')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.userInf')),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.AddField(
            model_name='phonesinf',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='gradesinf',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='aboutinf',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='serviceApp.userInf'),
        ),
    ]
