# Generated by Django 2.0.3 on 2018-03-13 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='myServerMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostName', models.CharField(max_length=30)),
                ('IPAddress', models.GenericIPAddressField()),
                ('hostUrl', models.URLField()),
                ('hostPort', models.IntegerField()),
                ('createTime', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-createTime'],
            },
        ),
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('userNo', models.IntegerField(primary_key=True, serialize=False)),
                ('userPasswd', models.TextField()),
            ],
        ),
    ]
