# Generated by Django 2.0.4 on 2018-05-15 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='aboutInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about_title', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=255)),
                ('about_content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='carParts',
            fields=[
                ('partId', models.AutoField(primary_key=True, serialize=False)),
                ('partName', models.CharField(max_length=40)),
                ('partNumber', models.IntegerField()),
                ('partType', models.CharField(max_length=10)),
                ('partSize', models.CharField(max_length=40)),
                ('partPrice', models.FloatField()),
                ('partDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='commitDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_details', models.CharField(max_length=255)),
                ('commit_status', models.BooleanField(default=False)),
                ('commit_time', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['commit_time'],
            },
        ),
        migrations.CreateModel(
            name='gradesInf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_grade', models.FloatField()),
                ('user_message', models.TextField()),
                ('ava_grade', models.FloatField()),
                ('grade_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='phonesInf',
            fields=[
                ('phone_id', models.AutoField(primary_key=True, serialize=False)),
                ('phone_name', models.CharField(max_length=30)),
                ('image_path', models.CharField(max_length=255)),
                ('phone_details', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='repairInfo',
            fields=[
                ('repairId', models.AutoField(primary_key=True, serialize=False)),
                ('repairName', models.CharField(max_length=40)),
                ('totalPrice', models.FloatField()),
                ('repairDetails', models.CharField(max_length=255)),
                ('partDetails', models.CharField(max_length=255)),
                ('repairDate', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='userInf',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_name', models.CharField(max_length=30)),
                ('user_nickname', models.CharField(max_length=30)),
                ('user_grant', models.BooleanField(default=False)),
                ('user_sex', models.CharField(max_length=5)),
                ('user_mask', models.CharField(max_length=100)),
                ('image_path', models.CharField(default=None, max_length=255)),
                ('user_grades', models.FloatField(default=0.0)),
                ('user_passwd', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='workOrders',
            fields=[
                ('order_id', models.AutoField(primary_key=True, serialize=False)),
                ('order_title', models.CharField(max_length=30)),
                ('order_details', models.CharField(max_length=255)),
                ('order_status', models.BooleanField(default=False)),
                ('order_grade', models.FloatField(default='0.0')),
                ('order_time', models.DateTimeField(auto_now_add=True)),
                ('phone_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviceApp.phonesInf')),
                ('server_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_server', to='serviceApp.userInf')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='work_user', to='serviceApp.userInf')),
            ],
            options={
                'ordering': ['-order_time'],
            },
        ),
        migrations.AddField(
            model_name='repairinfo',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='repair_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='phonesinf',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='phones_admin', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='gradesinf',
            name='grade_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_order', to='serviceApp.workOrders'),
        ),
        migrations.AddField(
            model_name='gradesinf',
            name='server_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='serviceApp.workOrders'),
        ),
        migrations.AddField(
            model_name='gradesinf',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='grade_user', to='serviceApp.workOrders'),
        ),
        migrations.AddField(
            model_name='commitdetails',
            name='commit_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commit_from_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='commitdetails',
            name='commit_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commit_order', to='serviceApp.workOrders'),
        ),
        migrations.AddField(
            model_name='commitdetails',
            name='commit_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='commit_to_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='carparts',
            name='personId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='admin_user', to='serviceApp.userInf'),
        ),
        migrations.AddField(
            model_name='aboutinf',
            name='admin_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='about_admin', to='serviceApp.userInf'),
        ),
    ]
